In [6]:
from tensorflow import keras
from keras.datasets import mnist
import numpy as np

In [47]:
input_dim = 784
original_inputs = keras.Input(shape = input_dim,)
base_model = keras.layers.Dense(64, activation=keras.activations.relu)(original_inputs)
base_model = keras.layers.Dense(10, activation=keras.activations.softmax)(base_model)

In [48]:
(x_train, y_train), (x_test, y_test) =  mnist.load_data()
x_train.shape

(60000, 28, 28)

In [49]:
x_train = x_train.reshape((x_train.shape[0], np.prod(x_train.shape[1:]))).astype("float32")/255
x_train[0:3,400:410]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.31764707, 0.9411765 , 0.99215686, 0.99215686, 0.46666667],
       [0.99215686, 0.74509805, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.18431373, 0.19215687, 0.45490196, 0.5647059 ,
        0.5882353 , 0.94509804, 0.9529412 , 0.91764706, 0.7019608 ]],
      dtype=float32)

In [53]:
model = keras.Model(inputs=original_inputs, outputs=base_model)
model.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)
model.summary()

Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_17 (Dense)             (None, 64)                50240     
_________________________________________________________________
dense_18 (Dense)             (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [51]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [55]:
model.fit(x_train, y_train, batch_size=32, epochs=3)

Epoch 1/3
  41/1875 [..............................] - ETA: 2s - loss: 2.0627 - accuracy: 0.3232  

2021-08-13 17:02:59.429221: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 3s 1ms/step - loss: 0.6992 - accuracy: 0.8295
Epoch 2/3
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3369 - accuracy: 0.9063
Epoch 3/3
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2819 - accuracy: 0.9208


In [56]:
model.weights

[<tf.Variable 'dense_17/kernel:0' shape=(784, 64) dtype=float32, numpy=
 array([[-0.01773538, -0.07552434,  0.04510833, ..., -0.06886718,
         -0.00448252,  0.04239903],
        [-0.03232232, -0.00593152, -0.01338867, ...,  0.00974556,
         -0.00776657, -0.07413156],
        [-0.03103454, -0.02462777,  0.07080076, ..., -0.06989224,
          0.02870841, -0.03126393],
        ...,
        [ 0.03282062, -0.0589621 , -0.05940204, ..., -0.01933312,
         -0.02147094, -0.06911756],
        [-0.06926715, -0.04044408, -0.02345875, ...,  0.05692583,
          0.05666902, -0.01232243],
        [ 0.01784287, -0.0167395 ,  0.06807194, ..., -0.03277933,
         -0.06591885,  0.01842759]], dtype=float32)>,
 <tf.Variable 'dense_17/bias:0' shape=(64,) dtype=float32, numpy=
 array([ 0.02908643, -0.03435811,  0.09946196,  0.09005564, -0.03866997,
        -0.0005019 ,  0.06510757,  0.09790802, -0.03774636, -0.01145362,
        -0.04323366,  0.00634779,  0.03913045,  0.01974491, -0.0218022 ,


In [ ]:
class Linear(keras.layers.Layer): 

    """y = w.x + b""" 

    def __init__(self, units=32): 

        super(Linear, self).__init__() 
        self.units = units 

 
    def build(self, input_shape): 
        #note: add_weight is in the build, not in the init 
        self.w = self.add_weight( 
            shape=(input_shape[-1], self.units), 
            initializer="random_normal", 
            trainable=True, 
        ) 
        self.b = self.add_weight(shape=(self.units,), 
            initializer="random_normal", trainable=True ) 

    def call(self, inputs, verbose=False): 
        y = tf.matmul(inputs, self.w) + self.b 

        if verbose: 
            print(f"w:{self.w.numpy()}\n x:{inputs.numpy()}\nb:{self.b.numpy()}\n" 
            f"y=w.x + b :{y.numpy()}") 
        return y 

 
